### ISSUE TITLE
Keepass 

### ISSUE THREAD

**Issue by Raif1** [yogeshpaliyal/KeyPass#120] opened 2022-02-18 07:54 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add an option to use kdbx files or keepass type files to use as database . So then we will be able to use this app as keepass for android application which will be very nice . And the ui is great. 

**Describe alternatives you've considered**
Many keepass android implementations Keepassdx keepass2android etc. 

**Additional context**

**Comment by IJR222** [comment] 2022-03-24 22:51
This is a duplicate of #47

**Closed** 2022-08-18 17:06 UTC
